name: base

seed: 0

model:
  d_model: 512
  num_heads: 8
  vocab_size: 10000
  max_length: 1024
  d_ff: 2048
  num_enc_layers: 6
  num_dec_layers: 6
  dropout: 0.1

train:
  effective_batch_token_size: 20000
  minibatch_token_size: 512
  learning_rate: 1.0e-4  # 1 / (D_MODEL * WARM_UP_STEPS) ** 0.5
  adam_betas: [0.9, 0.98]
  adam_eps: 1.0e-9
  num_steps: 3000
  label_smoothing: 0.1
  device: cuda
  checkpoint_steps: 5
  warm_up_steps: 50
  models_dir: ./models
  resume: false
  validation_steps: 10
  validation_accum_steps: 1
  compile_model: false

data: 
  train_ds: techiaith/cardiff-university-tm-en-cy
  benchmark_ds: openlanguagedata/flores_plus
  max_length: 1024
  test_split_ratio: 0.1

tokenizers:
  vocab_size: 10000
  special_tokens:
    pad_token: "<pad>"
    unk_token: "<unk>"
    bos_token: "<s>"
    eos_token: "</s>"
  pad_token_id: 2
  training_size: 100000

locations:
  data_dir: ./data
  run_dir: ./runs
