name: test
seed: 0

model:
  d_model: 1024
  num_heads: 4
  vocab_size: 10000
  max_length: 64
  d_ff: 1024
  num_enc_layers: 2
  num_dec_layers: 2
  dropout: 0.1

train:
  effective_batch_token_size: 20000
  minibatch_token_size: 8192
  learning_rate: 1.0e-4  # 1 / (D_MODEL * WARM_UP_STEPS) ** 0.5
  adam_betas: [0.9, 0.98]
  adam_eps: 1.0e-9
  num_steps: 200
  label_smoothing: 0.1
  device: cuda
  checkpoint_steps: 5
  warm_up_steps: 5
  validation_steps: 5
  validation_batches: 1
  compile_model: true

data: 
  train:
    ds: techiaith/cardiff-university-tm-en-cy
    sample_size: 1000
    test_split_ratio: 0.1
  benchmark:
    ds: openlanguagedata/flores_plus
    sample_size: 1000
  

tokenizer:
  vocab_size: 10000
  special_tokens:
    pad_token: "<pad>"
    unk_token: "<unk>"
    bos_token: "<s>"
    eos_token: "</s>"
  pad_token_id: 2
  training_size: 1000

locations:
  data_dir: ./data
  runs_dir: ./runs
